project:
  type: website

website:
  title: "Robert J. Tulmen"
  navbar:
    left:
    - text: "Home"
      href: index.html
    - text: "Purpose"
      href: purpose.html
    - text: "Research"
      href: research.html
    - text: "CV"
      href: cv.pdf
    - text: "Insight on Data and ML"
      href: assignment2.html
    - text: "Election Data Discrepancies"
      href: assignment3.html
    - text: "Tech Study"
      href: techstudy.html
    - text: "Web Scraping"
      href: webscraping.html
    


format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true

editor: visual