project:
  type: website

website:
  title: "Robert J. Tulmen"
  navbar:
    left:
    - text: "Home"
      href: index.html
    - text: "Purpose"
      href: purpose.html
    - text: "Research"
      href: research.html
    - text: "CV"
      href: cv.pdf
    - text: "Assignment 1"
      href: assignment1.html
    - text: "Assignment 2"
      href: assignment2.html
    


format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true

editor: visual