---
title: "Weekly Reflections"
---

# Reflections

## Week 1

In my experience using AI and observing how others use AI as a part of the OIT team at UTD, it has become an all encompassing tool for students to tackle any kind of project that they may encounter during their studies here at the University. At times relied on too much, artificial intelligence will inevitably be integrated into our daily lives at one point or another... In my opinion it's important for users to understand certain things...

### Rules, Guidelines, and Tendencies

1.  It's imperative, that users understand that once certain **LLMs** take in **PII**, you are essentially forfeiting your privacy...
2.  LLMs should be used as supplemental knowledge and not the basis for claims, actionable knowledge, or a primary source. These models are drawing from elsewhere anyways which, not only excludes it form being a ***primary source***, but should be carefully vetted if that information is going to be passed on to something/somebody else.
3.  Multiple models should be used especially for items such as peer review or journal articles. As predictive outputs have been found to make up unfinished articles and lay claims to somethings that haven't been studied, but will be investigated, but is present in said articles.

### Originality and AGI

AI isn't quite at the turning point to which it will completely erase originality in terms artistic or creative ability. A somewhat solid rebuttal to this effect is sculpting, pottery, or architecture, which are artisanal fields that still exist in today's day and age alongside machinery that can pretty much sculpt better than Donatello... To that point, I would like to believe that most educated people can come to the conclusion that things have been AI doctored the same way they can tell that things have been machine made. Making hand crafted goods, or these previously mentioned "artisanal fields" still very much desirable goods/services.

As for Artificial General Intelligence, my thoughts are somewhat similar to the argument that I'm making above, in that even though LLMs might be able to convey human reasoning to some degree (my brain instantly goes to therapy or psychology in these matters) the beauty in most previously written works that have been bestowed upon the human race in some form of knowledge is the "***human factor***". Being able to have multiple perspectives can lead to innovation and inquiry that I suppose only comes from different minds. I can read Marcus Aurelius' ***Meditations*** before I go to sleep at night and might gather some different idea from his anecdotal perspective of stoicism than someone else might. I don't think AGI (in this current day and age) will be able to appropriately convey that sentiment.

## Week 2

### Using AI for Project Purposes

There are a couple of ways off the top of my head that I can think of, for example:

A. Citation machine

B. Summarization of large documents to which don't pertain to my field (potentially gaining an understanding from the perspective of someone in that field)

C. Ping Pong Partner (A lot of times I use it in terms of a wall I can bounce ideas off of)

D. Initialization (I find the beginning of my journey when writing things is the most difficult part, and it's nicer to build off a foundation rather than staring at a blank page)

For these purposes I will probably be using a combination of Gemini, Claude, and Microsoft's CoPilot as we have easy access via the University.

## Week 3

### Derivation of Knowledge and The Difference Between Information

One can think of data, information, knowledge, and wisdom as a hierarchy of sorts...

Data (either discovered or found) translated -\> into information, which makes sense of the raw data -\> an accumulation of information develops actionable insights that might be of use (or not, which one could argue - the most classic example being, "you didn't fail to make something 1,000 times you just figured out how to not make something 1,000 times - is similar in this event) turns into knowledge -\> and eventually an accumulation of said "knowledge" bank leads to wisdom, which is experience. Deriving my thoughts from my studies and this class I would say that the difference between information and knowledge is easily translatable to something like this:\

Raw Data -\> Cake Ingredients

Information -\> Recipe

Knowledge -\> The Technique (required to make the cake)

Wisdom -\> Mastery Experience to the craft

All in all, it's important to understand the four levels of curiosity displayed in this analogy which are: what = raw data, who/where/when = information, how = knowledge, and the last but arguably the most important, why = wisdom.

## AI Discrepancies and Failures

In my past experience (and I'll preface this next thought here that I DID NOT USE AI FOR THESE OPINIONS, which I feel is important to mention when speaking on a subject such as this one) using AI for an assortment of things, one could argue that there's a plethora of different responses that you can get from prompting an LLM especially in regards to high level questions that you might needs answers to. I would also argue the field of GIS is a pretty niche field in relation to others and when prompting it questions I might have when using certain programs it definitely reaches and delivers hallucinations at times especially when the specificity gets narrower. One of my group members in class also happened to mention the fact that Gemini remembers inputs you might have previously used, and even when starting new chats it will still make callbacks to some of those inputs, which in regards to commonsensical things is extremely frustrating because the problem you're trying to solve might have slight differences or calls for "niche" responses.
